name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'

jobs:
  test-and-build:
    name: Test and build
    runs-on: ubuntu-latest
    steps:

    - name: Download go@v1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
        
    - name: Checkout repo
      uses: actions/checkout@v1
      
    - name: Download deps
      run: go mod download

    - name: Test
      run: go test ./... -v -race

    - name: Build
      run: make build

    - name: Create binaries for release
      if: startsWith(github.ref, 'refs/tags/')
      run: bash release.sh

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: release/*
      env:
        GITHUB_TOKEN: ${{ secrets.GHUB_TOKEN }}