name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
    tags:
      - "v*.*.*"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v1

      - name: Download go@v1.14
        uses: actions/setup-go@v1
        with:
          go-version: 1.14

      - name: Download deps
        run: go mod download

      - name: Test
        run: go test ./... -v -race
  release:
    name: Release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout repo
        uses: actions/checkout@v1

      - name: Download go@v1.14
        uses: actions/setup-go@v1
        with:
          go-version: 1.14

      - name: Build
        run: make

      - name: Create binaries for release
        run: bash release.sh

      - name: Add binaries to release
        uses: softprops/action-gh-release@v1
        with:
          files: release/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
